language: java
before_cache:
- find $HOME/.m2/ -type d -name '*-SNAPSHOT' -exec rm -rf {} \; 2>/dev/null
cache:
  directories:
    - $HOME/.m2
jdk: oraclejdk8
sudo: required
install:
  - chmod +x .travis/install-mariadb.sh
  - sudo .travis/install-mariadb.sh
before_script: mysql -uroot < .travis/create-db.sql
script: mvn -Dspring.datasource.password= verify
